# Generated by Django 5.1.7 on 2025-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0002_produto_estoque_alter_estoque_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='data',
            field=models.DateField(verbose_name='Data da Nota Fiscal'),
        ),
    ]
