# Generated by Django 5.1.7 on 2025-03-08 17:26

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0002_alter_paciente_cpf_alter_paciente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cnes',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
    ]
