# Generated by Django 5.1.7 on 2025-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0003_remove_produto_estoque_alter_entradaestoque_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
