# Generated by Django 5.1.7 on 2025-03-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0003_alter_paciente_cnes_alter_paciente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
        migrations.AlterField(
            model_name='produto',
            name='apresentacao',
            field=models.CharField(max_length=50),
        ),
    ]
