# Generated by Django 5.1.7 on 2025-03-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0004_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='apresentacao',
            field=models.CharField(max_length=50, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('motivo', models.TextField()),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgis.produto')),
            ],
        ),
    ]
