# Generated by Django 5.1.7 on 2025-03-23 10:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0005_alter_endereco_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaestoque',
            name='data',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='valor',
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='validade',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='ItemEntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sgis.entradaestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgis.produto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nota', models.DateField(verbose_name='Data da Nota Fiscal')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgis.fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='nota_fiscal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='sgis.notafiscal'),
        ),
    ]
