# Generated by Django 5.1.7 on 2025-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0006_remove_entradaestoque_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='numero_nota_fiscal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Número da Nota Fiscal'),
        ),
    ]
