# Generated by Django 5.1.7 on 2025-03-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0007_notafiscal_numero_nota_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaestoque',
            name='nota_fiscal',
        ),
    ]
