# Generated by Django 5.1.7 on 2025-03-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0008_remove_entradaestoque_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaestoque',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgis.notafiscal'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero_nota_fiscal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Número da Nota Fiscal'),
        ),
    ]
