# Generated by Django 5.1.7 on 2025-04-12 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgis', '0013_itementradaestoque_quantidade_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
